export interface AllocationConfig {
  flexicap: number;
  midcap: number;
  smallcap: number;
  largecap: number;
  elss: number;
  international: number;
  gold: number;
  debt: number;
  hybrid: number;
  liquid: number;
}

export const PERSONA_ALLOCATIONS: Record<string, AllocationConfig> = {
  'Young Growth Investor': {
    flexicap: 35,
    midcap: 25,
    smallcap: 20,
    largecap: 0,
    elss: 0,
    international: 10,
    gold: 5,
    debt: 0,
    hybrid: 0,
    liquid: 5,
  },
  'Wealth Builder': {
    flexicap: 30,
    midcap: 20,
    smallcap: 10,
    largecap: 15,
    elss: 0,
    international: 10,
    gold: 5,
    debt: 5,
    hybrid: 0,
    liquid: 5,
  },
  'Long-Term Compounder': {
    flexicap: 30,
    midcap: 20,
    smallcap: 15,
    largecap: 10,
    elss: 0,
    international: 10,
    gold: 5,
    debt: 5,
    hybrid: 0,
    liquid: 5,
  },
  'Retirement Planner': {
    flexicap: 20,
    midcap: 10,
    smallcap: 5,
    largecap: 15,
    elss: 0,
    international: 5,
    gold: 10,
    debt: 20,
    hybrid: 10,
    liquid: 5,
  },
  'Income Seeker': {
    flexicap: 0,
    midcap: 0,
    smallcap: 0,
    largecap: 5,
    elss: 0,
    international: 0,
    gold: 5,
    debt: 50,
    hybrid: 30,
    liquid: 10,
  },
  'Capital Preservation Investor': {
    flexicap: 0,
    midcap: 0,
    smallcap: 0,
    largecap: 0,
    elss: 0,
    international: 0,
    gold: 10,
    debt: 55,
    hybrid: 20,
    liquid: 15,
  },
  'Tax Saver': {
    flexicap: 0,
    midcap: 0,
    smallcap: 0,
    largecap: 0,
    elss: 60,
    international: 0,
    gold: 5,
    debt: 15,
    hybrid: 15,
    liquid: 5,
  },
  'Family Goal Planner': {
    flexicap: 25,
    midcap: 15,
    smallcap: 10,
    largecap: 15,
    elss: 0,
    international: 10,
    gold: 5,
    debt: 10,
    hybrid: 5,
    liquid: 5,
  },
  'Conservative Investor': {
    flexicap: 0,
    midcap: 0,
    smallcap: 0,
    largecap: 10,
    elss: 0,
    international: 0,
    gold: 10,
    debt: 50,
    hybrid: 20,
    liquid: 10,
  },
  'Balanced Investor': {
    flexicap: 20,
    midcap: 10,
    smallcap: 5,
    largecap: 15,
    elss: 0,
    international: 5,
    gold: 5,
    debt: 25,
    hybrid: 10,
    liquid: 5,
  },
  'Aggressive Growth Investor': {
    flexicap: 30,
    midcap: 25,
    smallcap: 20,
    largecap: 0,
    elss: 0,
    international: 10,
    gold: 5,
    debt: 0,
    hybrid: 0,
    liquid: 10,
  },
  'Experienced Opportunistic Investor': {
    flexicap: 25,
    midcap: 25,
    smallcap: 20,
    largecap: 0,
    elss: 0,
    international: 15,
    gold: 5,
    debt: 0,
    hybrid: 5,
    liquid: 5,
  },
};
